
spring:
  application:
    name: forfun-admin
  profiles:
    active: @profiles.active@
  cloud:
    config:
      enabled: false
  boot:
    admin:
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,flyway,liquibase,heapdump,loggers
server:
  port: ${port:9090}
endpoints:
  health:
    sensitive: false

---

#dev环境
spring:
  profiles: native
#  boot:
#    admin:
#      turbine:
#        clusters: default
#        url: http://localhost:8989/turbine.stream
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

---
spring:
  profiles: sit,prod
#  boot:
#    admin:
#      turbine:
#        clusters: default
#        url: http://forfun-admin:8989/turbine.stream
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://forfun-eureka:8761/eureka

